#!/bin/bash
################################################
#       __                 ______
#  ____/ /___  ____  ___  / / __ \___ _   __
# / __  / __ \/ __ \/ _ \/ / / / / _ \ | / /
#/ /_/ / /_/ / /_/ /  __/ / /_/ /  __/ |/ /
#\__,_/\____/ .___/\___/_/_____/\___/|___/
#          /_/
#
################################################
#Date : Tue 05 Jan 2021 05:26:33 AM -05
#GitHub :  https://github.com/dopelDev
#Facebook : https://www.facebook.com/profile.php?id=100036185774355
#Mail : 322kuroneko2@gmail.com
################################################
if [[ $1 = '-dir' ]]; then
  date +%a-%F;
else
  num=$(date +%d)
  case $num in
    01) inwords='one';;
    02) inwords='two';;
    03) inwords='three';;
    04) inwords='four';;
    05) inwords='five';;
    06) inwords='six';;
    07) inwords='seven';;
    08) inwords='eight';;
    09) inwords='nine';;
    10) inwords='ten';;
    11) inwords='eleven';;
    12) inwords='twelve';;
    13) inwords='thirteen';;
    14) inwords='fourteen';;
    15) inwords='fifteen';;
    16) inwords='sixteen';;
    17) inwords='seventeen';;
    18) inwords='eighteen';;
    19) inwords='nineteen';;
    20) inwords='twenty';;
    21) inwords='twenty-one';;
    22) inwords='twenty-two';;
    23) inwords='twenty-three';;
    24) inwords='twenty-four';;
    25) inwords='twenty-five';;
    26) inwords='twenty-six';;
    27) inwords='twenty-seven';;
    28) inwords='twenty-eight';;
    29) inwords='twenty-nine';;
    30) inwords='thirty';;
    31) inwords='thirty-one';;
  esac
  date +%B%n%A%n%d
  echo $inwords
  date +%Y
fi
